// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0VmTVJMiOYhNoJPcl0FVCfjorEHUvBs0',
    appId: '1:581885601245:android:842c62f4677a37468b0234',
    messagingSenderId: '581885601245',
    projectId: 'fir-upload-image-51965',
    databaseURL: 'https://fir-upload-image-51965.firebaseio.com',
    storageBucket: 'fir-upload-image-51965.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArU8OBfxS4WPMe9hIzZ0PpUKD-cF5XNDY',
    appId: '1:581885601245:ios:fa45cb71c270879a8b0234',
    messagingSenderId: '581885601245',
    projectId: 'fir-upload-image-51965',
    databaseURL: 'https://fir-upload-image-51965.firebaseio.com',
    storageBucket: 'fir-upload-image-51965.appspot.com',
    androidClientId: '581885601245-g79c7mvloi5lftremmeae0l8sr6bb83p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flavorsTodoApp',
  );
}
